---
- name: '[Darwin] Make sure vim is installed'
  homebrew:
    name: vim
    state: present
  become: no
  tags: vim

- name: '[Darwin] Check which SHELL is running'
  command: "echo ${SHELL}"
  register: vim_shell
  changed_when: false
  tags: vim

- name: '[Darwin] Set vim as a default editor for visudo in ~/bash_profile if using bash'
  lineinfile:
    path: ~/.bash_profile
    regexp: '^.*export\sEDITOR=.*'
    line: 'export EDITOR=vim visudo'
  when: vim_shell.stdout is search('bash')
  #when: "vim_shell.stdout.find('v=' ~ /bash) == -1"  # should look similar to this in ansible 2.9

- name: '[Darwin] Set vim as a default editor for visudo in ~/.zshrc if using zsh'
  lineinfile:
    path: ~/.zshrc
    regexp: '^.*export\sEDITOR=.*'
    line: 'export EDITOR=vim visudo'
  when: vim_shell.stdout is search('zsh')
  #when: "vim_shell.stdout.find('v=' ~ /zsh) == -1"  # should look similar to this in ansible 2.9

- name: '[Darwin] Set TERM environment variable in ~/.bash_profile if using bash'
  lineinfile:
    path: ~/.bash_profile
    regexp: '^.*export\sTERM=.*'
    line: 'export TERM="xterm-256color"'
  when: vim_shell.stdout is search('bash')
  #when: "vim_shell.stdout.find('v=' ~ /bash) == -1"  # should look similar to this in ansible 2.9


- name: '[Darwin] Set TERM environment variable in ~/.zshrc if using zsh'
  lineinfile:
    path: ~/.zshrc
    regexp: '^.*export\sTERM=.*'
    line: 'export TERM="xterm-256color"'
  when: vim_shell.stdout is search('zsh')
  #when: "vim_shell.stdout.find('v=' ~ /zsh) == -1"  # should look similar to this in ansible 2.9
...
