---
- name: '[dependencies] Non-MacOS: Install git and CTags'
  package:
    name:
    - git
    - exuberant-ctags
    state: present
  become: yes
  register: vim_dep_result
  until: vim_dep_result is succeeded
  when: ansible_os_family != 'Darwin'
  tags:
  - vim
  - vim_dependencies

- name: '[dependencies] MacOS: Install git'
  homebrew:
    name:
    - git
    state: present
  become: no
  register: vim_dep_result
  until: vim_dep_result is succeeded
  when: ansible_os_family == 'Darwin'
  tags:
  - vim
  - vim_dependencies
...
